//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YbanezNacua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long id { get; set; }
        public string username { get; set; }
        public string feedback1 { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }
    }
}
